### ISSUE TITLE
Source images for Blog Posts

### ISSUE THREAD

**Issue by melissakeizer** [swmcc/swmcc.github.io#37]
Source images for cover photos for blog posts. There's A LOT of posts so even the most recent ones so browsing the first few pages of the blog index will show posts with unique images.

We can use a placeholder image for the rest.

**Comment by melissakeizer** [comment]
Oh, here's a list of good free stock sites to make this easier :) 

Unsplash 
One of my favourites
https://unsplash.com/

PicJumbo
https://picjumbo.com

ISO Republic
Easy to search for specific subjects
http://isorepublic.com/

IM FREE
Lots of decent business related ones here
http://www.imcreator.com/free

So these ones are full of quite random photos but there might be a few gems! 

Gratisography
http://www.gratisography.com/

GetRefe
http://getrefe.tumblr.com/archive

I also use Flickr Creative Commons occasionally too, they have lots of images available but you have to check what type of license they're using. 
https://www.flickr.com/creativecommons/

**Comment by swmcc** [comment]
Class - what sizes do I need to get these to work on the site? Gonna whack it in a grunt task or even a gulp (never used gulp before). :)

**Comment by melissakeizer** [comment]
Awesome, I'm curious as to how to incorporate Grunt and Gulp into my workflow so interested in how you get on with that! :) 

For blog and project list items images dimensions should be - 680px x 340
For header/cover images - 1440 x 720

Though it would be good to have those cover images optimised so they don't take forever to load. I usually save images for the web out at 75% quality.

**Comment by swmcc** [comment]
I use grunt in the current site at the mo - not sure it is a good thing though... Well grunt that is. Will see :) :+1:  on all this by the way

**Comment by swmcc** [comment]
Got image resize working on my laptop now. Will refine it and add it into the workflow of creating a new blog page. Gulp is quite nice.. details will be in the readme. Will probably only do 2012+ articles. So will give this a good testing doing that :)
