### ISSUE TITLE
Filtering functionality in Blog Index page

### ISSUE THREAD

**Issue by melissakeizer** [swmcc/swmcc.github.io#38]
See the wireframes to view what I had in mind regarding this. I can style it up afterwards. Is this how you would like it to work too Stephen?

1. Show categories link shown on page. Click this to reveal list of tags below. 
2. User can click on a tag to show all posts with this tag. 
3. The "show categories" link should behave like a toggle, so the user can hide the list of tags when clicking it again

**Comment by swmcc** [comment]
New way of filtering the blog articles will be created as discussed.
