### ISSUE TITLE
Add Pagination to Blog Index

### ISSUE THREAD

**Issue by melissakeizer** [swmcc/swmcc.github.io#39]
Hey Stephen, do you wanna take care of the pagination for the blog? 

In my wireframes I have it showing a number of blog posts (maybe 8 is a good number?) then a button that says "load older posts." This loads the next 8. However, you could use page numbers instead, whatever you prefer!

If you wanna add the functionality for this i'll style up anything that needs styling :)

**Comment by swmcc** [comment]
Ok I will.. I'll get all this done at the weekend.
